//*************************************************
//* Header file for TDialog
//* ABOUT.H
//*************************************************

#ifndef __ABOUT_H_INCLUDED
#define __ABOUT_H_INCLUDED

#define Uses_TButton
#define Uses_TLabel
#define Uses_TStaticText
#define Uses_TParamText
#define Uses_TMemo
#define Uses_TListBox
#define Uses_TSortedListBox
#define Uses_TScrollBar
#define Uses_THistory
#define Uses_TInputLine
#define Uses_TCheckBoxes
#define Uses_TRadioButtons
#define Uses_TPXPictureValidator
#define Uses_TStringCollection
#define Uses_TStringLookupValidator
#define Uses_TRangeValidator
#define Uses_TDialog
#define Uses_TSItems

#include <tv.h>

TDialog *makeAboutBox(void);


#endif

