@echo off
echo Installation starts....
rem ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
rem ³ This is a simple installation batch.                 ³
rem ³ It is needed, because the naming of the files must be³
rem ³ Borland-forum-appropriate.                           ³
rem ³ (Don't ask me)                                       ³
rem ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
echo Copying files...
copy hftp.* helpfile.*>nul
rem that's it.
echo Installation complete!
